### ISSUE TITLE
L is not defined

### ISSUE THREAD

**Issue by nelsonlarocca** [M-Gregoire/Nuxt-Leaflet#5]
that's using Universal Mode, Nuxt version 2.8.1

plus this compiler warning
 ERROR  Failed to compile with 1 errors                                                                                                   friendly-errors 23:42:01

 ERROR  in ./pages/user/map2.vue                                                                                                          friendly-errors 23:42:01

Module Error (from ./node_modules/eslint-loader/index.js):                                                                                friendly-errors 23:42:01

C:\Projects\NUXT\yamenu\pages\user\map2.vue
  8:19  error  'L' is not defined  no-undef
  9:5   error  'L' is not defined  no-undef

**Comment by M-Gregoire** [comment]
Hello,

Sorry I took so look to answer, I missed the notification about this issue. 

I haven't used this plugin for quite some time but `L is not defined` looks like a missing import. Are you sure your plugin is well defined and that you added it to `nuxt.config.js` as described in the README?
