### ISSUE TITLE
Add l-moving-marker component 

### ISSUE THREAD

**Issue by pcm0nk** [M-Gregoire/Nuxt-Leaflet#6]
Im trying to add https://github.com/LouisMazel/vue2-leaflet-movingmarker to the library, How can I add this as a plugin to the library?
What I did is I installed it then added ```import LMovingMarker from 'vue2-leaflet-movingmarker'
``` to my leaflef plugin in nuxt plugins folder and adding ```Vue.component('l-moving-marker', LMovingMarker); ``` at the  end , but when leaflet map opens it throws error that `did you register the component properly`.
```
// leafletmap plugin.js for nuxt
import Vue from 'vue';
import {LMap, LTileLayer, LMarker , LIconDefault, LPopup} from 'vue2-leaflet';
import {VGeosearch} from 'vue2-leaflet-geosearch';
import LMovingMarker from 'vue2-leaflet-movingmarker'
import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
})

Vue.component('l-map', LMap);
Vue.component('l-tilelayer', LTileLayer);
Vue.component('l-marker', LMarker);
Vue.component('l-popup', LPopup);
Vue.component('l-icon-default', LIconDefault);
Vue.component('v-geosearch', VGeosearch);
Vue.component('l-moving-marker', LMovingMarker);
```
thanks for any help

**Comment by M-Gregoire** [comment]
So everything works perfectly until you had those both lines:
```
import LMovingMarker from 'vue2-leaflet-movingmarker'
...
Vue.component('l-moving-marker', LMovingMarker);
```

Is that right?

**Comment by pcm0nk** [comment]
Tnx for coming back to me.well everything works, but I still dont see the l-moving-marker  and I get the did u register the component correctly or not but I do have the map

**Comment by M-Gregoire** [comment]
I haven't done Vue.js for a while now so I'm not sure I can help you here. Have you tried reaching out to the `l-moving-marker` author? 

This doesn't related to my explanation on how to make Nuxt and leaflet work together.

**Comment by pcm0nk** [comment]
No I didnt contact the author which I will, thought u might have some insights or maybe you did it already.
thanks anyway
