### ISSUE TITLE
can't found the support for edgemarker 

### ISSUE THREAD

**Issue by zeeshanweb-official** [M-Gregoire/Nuxt-Leaflet#7]
hi i wanna implement a library with this module 
here is the github link of edgemarker
https://github.com/ubergesundheit/Leaflet.EdgeMarker
is there any method to implement it with nuxt js???

**Comment by M-Gregoire** [comment]
I haven't woked with Vue.js nor Nuxt for a while now so I'm afraid I can't help you.

Good luck.
