### ISSUE TITLE
Importing the library

### ISSUE THREAD

**Issue by carlosalbaladejo** [M-Gregoire/Nuxt-Leaflet#9]
Looking at Vue-Leaflet [docs](https://github.com/vue-leaflet/Vue2Leaflet#importing-the-library-in-webpack--rollup), looks like the new way to import the library is this:

```js
# Full library
import * as Vue2Leaflet from 'vue2-leaflet'; // VALID

# Just the necessary
import { LMap, LTileLayer, LMarker } from 'vue2-leaflet';
```

So the plugin now should look like this:

```js
import Vue from 'vue'
import { LMap, LTileLayer, LMarker } from 'vue2-leaflet'
const VueLeaflet = {
  install(Vue, options) {
    Vue.component('l-map', LMap)
    Vue.component('l-marker', LMarker)
    Vue.component('l-tile-layer', LTileLayer)
  }
};
Vue.use(VueLeaflet);
export default VueLeaflet;
```

**Comment by M-Gregoire** [comment]
Thanks a lot for your contribution !

I've updated the documentation in https://github.com/M-Gregoire/Nuxt-Leaflet/commit/baf1426d57add424ddafcdb6aa404b32924a049b.
